export const coinPredictions: Map<string, string> = new Map<string, string>();
coinPredictions.set(
  "ETH",
  "https://coincodex.com/crypto/ethereum/price-prediction/"
  );
  coinPredictions.set(
    "BTC",
    "https://coincodex.com/crypto/bitcoin/price-prediction/"
);
coinPredictions.set(
  "WOO",
  "https://coincodex.com/crypto/wootrade/price-prediction/"
);
coinPredictions.set(
  "ALPHA",
  "https://coincodex.com/crypto/alpha-finance-lab/price-prediction/"
);
coinPredictions.set(
  "DOGE",
  "https://coincodex.com/crypto/dogecoin/price-prediction/"
);
coinPredictions.set(
  "SOL",
  "https://coincodex.com/crypto/solana/price-prediction/"
);
coinPredictions.set(
  "XRP",
  "https://coincodex.com/crypto/ripple/price-prediction/"
);
coinPredictions.set(
  "LINA",
  "https://coincodex.com/crypto/lina-review/price-prediction/"
);
coinPredictions.set(
  "IDEX",
  "https://coincodex.com/crypto/idex/price-prediction/"
);
coinPredictions.set(
  "LTC",
  "https://coincodex.com/crypto/litecoin/price-prediction/"
);
coinPredictions.set(
  "RNDR",
  "https://coincodex.com/crypto/render-token/price-prediction/"
);
coinPredictions.set(
  "ADA",
  "https://coincodex.com/crypto/cardano/price-prediction/"
);
coinPredictions.set(
  "SHIB",
  "https://coincodex.com/crypto/shiba-inu/price-prediction/"
);
coinPredictions.set(
  "DOT",
  "https://coincodex.com/crypto/polkadot/price-prediction/"
);
coinPredictions.set(
  "ATOM",
  "https://coincodex.com/crypto/cosmos/price-prediction/"
);
coinPredictions.set(
  "TRX",
  "https://coincodex.com/crypto/tron/price-prediction/"
);
coinPredictions.set(
  "AVAX",
  "https://coincodex.com/crypto/avalanche/price-prediction/"
);
coinPredictions.set(
  "RLC",
  "https://coincodex.com/crypto/iexec-rlc/price-prediction/"
);
coinPredictions.set(
  "APT",
  "https://coincodex.com/crypto/aptos/price-prediction/"
);
coinPredictions.set(
  "INJ",
  "https://coincodex.com/crypto/injective-protocol/price-prediction/"
);
coinPredictions.set(
  "LINK",
  "https://coincodex.com/crypto/chainlink/price-prediction/"
);
coinPredictions.set(
  "MATIC",
  "https://coincodex.com/crypto/matic-network/price-prediction/"
);
coinPredictions.set(
  "ICP",
  "https://coincodex.com/crypto/internet-computer/price-prediction/"
);
coinPredictions.set(
  "FIL",
  "https://coincodex.com/crypto/filecoin/price-prediction/"
);
coinPredictions.set(
  "DASH",
  "https://coincodex.com/crypto/dash/price-prediction/"
);
coinPredictions.set(
  "WETH",
  "https://coincodex.com/crypto/weth/price-prediction/"
);
coinPredictions.set(
  "ALPINE",
  "https://coincodex.com/crypto/alpine-f1-team-fan-token/price-prediction"
);
coinPredictions.set(
  "RAD",
  "https://coincodex.com/crypto/radicle/price-prediction/"
);
coinPredictions.set(
  "BNB",
  "https://coincodex.com/crypto/binance-coin/price-prediction/"
);
coinPredictions.set(
  "UMA",
  "https://coincodex.com/crypto/uma/price-prediction/"
);
coinPredictions.set(
  "AERGO",
  "https://coincodex.com/crypto/aergo/price-prediction/"
);
coinPredictions.set(
  "LUNC",
  "https://coincodex.com/crypto/terra/price-prediction/"
);
coinPredictions.set(
  "FTT",
  "https://coincodex.com/crypto/ftx-token/price-prediction/"
);
coinPredictions.set(
  "OP",
  "https://coincodex.com/crypto/optimism/price-prediction/"
);
coinPredictions.set(
  "CFX",
  "https://coincodex.com/crypto/conflux-network/price-prediction/"
);
coinPredictions.set(
  "JASMY",
  "https://coincodex.com/crypto/jasmy/price-prediction/"
);
coinPredictions.set(
  "GALA",
  "https://coincodex.com/crypto/gala/price-prediction/"
);
coinPredictions.set(
  "LINK",
  "https://coincodex.com/crypto/chainlink/price-prediction/"
);
coinPredictions.set(
  "FTM",
  "https://coincodex.com/crypto/fantom/price-prediction/"
);
coinPredictions.set(
  "BETA",
  "https://coincodex.com/crypto/beta-finance/price-prediction/"
);
coinPredictions.set(
  "AVAX",
  "https://coincodex.com/crypto/avalanche/price-prediction/"
);
coinPredictions.set(
  "FIL",
  "https://coincodex.com/crypto/filecoin/price-prediction/"
);
coinPredictions.set(
  "LDO",
  "https://coincodex.com/crypto/lido-dao/price-prediction/"
);
coinPredictions.set(
  "CAKE",
  "https://coincodex.com/crypto/pancakeswap/price-prediction/"
);
coinPredictions.set(
  "WIN",
  "https://coincodex.com/crypto/wintoken/price-prediction/"
);
coinPredictions.set(
  "COCOS",
  "https://coincodex.com/crypto/cocos-bcx/price-prediction/"
);
coinPredictions.set(
  "UNI",
  "https://coincodex.com/crypto/uniswap/price-prediction/"
);
coinPredictions.set(
  "XLM",
  "https://coincodex.com/crypto/stellar/price-prediction/"
);
coinPredictions.set(
  "XMR",
  "https://coincodex.com/crypto/monero/price-prediction/"
);

export const coinShort = (): string[] => {
  const temp: string[] = [];
  coinPredictions.forEach((v, k) => {
    temp.push(k);
  });
  return temp;
};
