export const coinShort: string[] = [
  "ETH",
  "WOO",
  "ALPHA",
  "DOGE",
  "SOL",
  "XRP",
  "LINA",
  "IDEX",
  "LTC",
  "RNDR",
  "ADA",
  "SHIB",
  "DOT",
  "ATOM",
  "TRX",
  "AVAX",
  "RLC",
  "APT",
  "INJ",
  "LINK",
  "MATIC",
  "ICP",
  "FIL",
  "DASH",
  "WETH",
  "ALPINE",
];

export const coinPredictions: Map<string, string> = new Map<string, string>();
coinPredictions.set(
  "ETH",
  "https://coincodex.com/crypto/ethereum/price-prediction/"
);
coinPredictions.set(
  "WOO",
  "https://coincodex.com/crypto/wootrade/price-prediction/"
);
coinPredictions.set(
  "ALPHA",
  "https://coincodex.com/crypto/alpha-finance-lab/price-prediction/"
);
coinPredictions.set(
  "DOGE",
  "https://coincodex.com/crypto/dogecoin/price-prediction/"
);
coinPredictions.set(
  "SOL",
  "https://coincodex.com/crypto/solana/price-prediction/"
);
coinPredictions.set(
  "XRP",
  "https://coincodex.com/crypto/ripple/price-prediction/"
);
coinPredictions.set(
  "LINA",
  "https://coincodex.com/crypto/lina-review/price-prediction/"
);
coinPredictions.set(
  "IDEX",
  "https://coincodex.com/crypto/idex/price-prediction/"
);
coinPredictions.set(
  "LTC",
  "https://coincodex.com/crypto/litecoin/price-prediction/"
);
coinPredictions.set(
  "RNDR",
  "https://coincodex.com/crypto/render-token/price-prediction/"
);
coinPredictions.set(
  "ADA",
  "https://coincodex.com/crypto/cardano/price-prediction/"
);
coinPredictions.set(
  "SHIB",
  "https://coincodex.com/crypto/shiba-inu/price-prediction/"
);
coinPredictions.set(
  "DOT",
  "https://coincodex.com/crypto/polkadot/price-prediction/"
);
coinPredictions.set(
  "ATOM",
  "https://coincodex.com/crypto/cosmos/price-prediction/"
);
coinPredictions.set(
  "TRX",
  "https://coincodex.com/crypto/tron/price-prediction/"
);
coinPredictions.set(
  "AVAX",
  "https://coincodex.com/crypto/avalanche/price-prediction/"
);
coinPredictions.set(
  "RLC",
  "https://coincodex.com/crypto/iexec-rlc/price-prediction/"
);
coinPredictions.set(
  "APT",
  "https://coincodex.com/crypto/aptos/price-prediction/"
);
coinPredictions.set(
  "INJ",
  "https://coincodex.com/crypto/injective-protocol/price-prediction/"
);
coinPredictions.set(
  "LINK",
  "https://coincodex.com/crypto/chainlink/price-prediction/"
);
coinPredictions.set(
  "MATIC",
  "https://coincodex.com/crypto/matic-network/price-prediction/"
);
coinPredictions.set(
  "ICP",
  "https://coincodex.com/crypto/internet-computer/price-prediction/"
);
coinPredictions.set(
  "FIL",
  "https://coincodex.com/crypto/filecoin/price-prediction/"
);
coinPredictions.set(
  "DASH",
  "https://coincodex.com/crypto/dash/price-prediction/"
);
coinPredictions.set(
  "WETH",
  "https://coincodex.com/crypto/weth/price-prediction/"
);
coinPredictions.set(
  "ALPINE",
  "https://coincodex.com/crypto/alpine-f1-team-fan-token/price-prediction"
);
