version: "3"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database 
    networks:
      - dockerNetwork
     
  database:
    build: ./dockerDatabase
    networks:
      - dockerNetwork
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cryptoScraper
    
  kali:
    build: ./kali
    volumes:
      - ./kali:/home
    networks:
      - dockerNetwork
  
networks:
  dockerNetwork:
    name: dockerNetwork
    