FROM kalilinux/kali-rolling
RUN apt update
RUN apt full-upgrade -y
RUN apt install iputils-ping -y
RUN apt install wget -y
RUN apt install nmap -y
RUN apt install vim -y
RUN apt install curl -y
WORKDIR /home
CMD ["sleep","infinity"]

